export const UNIT = {
  ALCRYST: 'Alcryst',
  ALEAR: 'Alear',
  ALFRED: 'Alfred',
  AMBER: 'Amber',
  ANNA: 'Anna',
  BOUCHERON: 'Boucheron',
  BUNET: 'Bunet',
  CELINE: 'Céline',
  CHLOE: 'Chloé',
  CITRINNE: 'Citrinne',
  CLANNE: 'Clanne',
  DIAMANT: 'Diamant',
  ETIE: 'Etie',
  FOGADO: 'Fogado',
  FRAMME: 'Framme',
  GOLDMARY: 'Goldmary',
  GREGORY: 'Gregory',
  HORTENSIA: 'Hortensia',
  IVY: 'Ivy',
  JADE: 'Jade',
  JEAN: 'Jean',
  KAGETSU: 'Kagetsu',
  LAPIS: 'Lapis',
  LINDON: 'Lindon',
  LOUIS: 'Louis',
  MADELINE: 'Madeline',
  MAUVIER: 'Mauvier',
  MERRIN: 'Merrin',
  NEL: 'Nel',
  PANDREO: 'Pandreo',
  PANETTE: 'Panette',
  RAFAL: 'Rafal',
  ROSADO: 'Rosado',
  SAPHIR: 'Saphir',
  SEADALL: 'Seadall',
  TIMERRA: 'Timerra',
  VANDER: 'Vander',
  VEYLE: 'Veyle',
  YUNAKA: 'Yunaka',
  ZELESTIA: 'Zelestia',
  ZELKOV: 'Zelkov',
}

export const JOB = {
  ARCHER: 'Archer',
  AVENIR: 'Avenir',
  AXE_ARMOR: 'Axe Armor',
  AXE_CAVALIER: 'Axe Cavalier',
  AXE_FIGHTER: 'Axe Fighter',
  AXE_FLIER: 'Axe Flier',
  BERSERKER: 'Berserker',
  BOW_KNIGHT: 'Bow Knight',
  CUPIDO: 'Cupido',
  DANCER: 'Dancer',
  DIVINE_DRAGON: 'Divine Dragon',
  DRAGON_CHILD: 'Dragon Child',
  ENCHANTER: 'Enchanter',
  FELL_CHILD: 'Fell Child',
  FELL_CHILD_NEL: 'Fell Child (Nel)',
  FELL_CHILD_RAFAL: 'Fell Child (Rafal)',
  GENERAL: 'General',
  GREAT_KNIGHT: 'Great Knight',
  GRIFFIN_KNIGHT: 'Griffin Knight',
  HALBERDIER: 'Halberdier',
  HERO: 'Hero',
  HIGH_PRIEST: 'High Priest',
  LANCE_ARMOR: 'Lance Armor',
  LANCE_CAVALIER: 'Lance Cavalier',
  LANCE_FIGHTER: 'Lance Fighter',
  LANCE_FLIER: 'Lance Flier',
  LINDWURM: 'Lindwurm',
  LORD_ALCRYST: 'Lord (Alcryst)',
  LORD_DIAMANT: 'Lord (Diamant)',
  MAGE: 'Mage',
  MAGE_CANNONEER: 'Mage Cannoneer',
  MAGE_KNIGHT: 'Mage Knight',
  MARTIAL_MASTER: 'Martial Master',
  MARTIAL_MONK: 'Martial Monk',
  MELUSINE: 'Melusine',
  NOBLE_ALFRED: 'Noble (Alfred)',
  NOBLE_CELINE: 'Noble (Céline)',
  PALADIN: 'Paladin',
  PICKET: 'Picket',
  ROYAL_KNIGHT: 'Royal Knight',
  SAGE: 'Sage',
  SENTINEL_FOGADO: 'Sentinel (Fogado)',
  SENTINEL_TIMERRA: 'Sentinel (Timerra)',
  SLEIPNIR_RIDER: 'Sleipnir Rider',
  SNIPER: 'Sniper',
  SUCCESSEUR: 'Successeur',
  SWORD_ARMOR: 'Sword Armor',
  SWORD_CAVALIER: 'Sword Cavalier',
  SWORD_FIGHTER: 'Sword Fighter',
  SWORD_FLIER: 'Sword Flier',
  SWORDMASTER: 'Swordmaster',
  THIEF: 'Thief',
  TIREUR_DELITE: 'Tireur d’élite',
  VIDAME: 'Vidame',
  WARRIOR: 'Warrior',
  WING_TAMER_HORTENSIA: 'Wing Tamer (Hortensia)',
  WING_TAMER_IVY: 'Wing Tamer (Ivy)',
  WOLF_KNIGHT: 'Wolf Knight',
  WYVERN_KNIGHT: 'Wyvern Knight',
}
